 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default
    
     steps:
       - checkout #pull source code from VCS
       - restore_cache:
           keys:
             - dotnet-packages-v1-{{ checksum "WpfApp1.csproj"}}
       - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
       - save_cache:
          paths:
            - C:\Users\16479\source\Nuget
          key: dotnet-packages-v1-{{ checksum "WpfApp1.csproj"}}
       - run:
          name: "Build using script"
          command: .\Scripts\build.ps1
       # TODO: sign app
