 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: 
        name: win/default
    
     steps:
       - checkout 
       #Note: defaults to checking out code over ssh (don't use this if you require it to be done over HTTPS)
       #- restore_cache:
       #    keys:
       #      - dotnet-packages-v1-{{ checksum "C:\Users\16479\source\repos\curly-succotash\WpfApp1"}}

       - run:
          name: "Install project dependencies"
          command: nuget restore .\WpfAppMain.sln

       #- save_cache: vstest.console.exe /Platform:x64 UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll
       #   paths:
       #     - C:\Users\16479\source\Nuget
       #   key: dotnet-packages-v1-{{ checksum "C:\Users\16479\source\repos\curly-succotash\WpfApp1"}}
       - run:
          name: "Build using script"
          command: .\Scripts\build.ps1

       - run:
          name: "Testing vstest"
          command: | 
             $env:PATH += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow"
             .\vstest.console.exe /Platform:x64 UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll

       - run:
          name: "Setup vstest and run tests"
          command: |
             cd C:\
             Resolve-Path -Path "Program Files (x86)" | cd
             cd "Microsoft Visual Studio\Installer"
             .\vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.Web -requiresAny -property installationPath | cd
             cd Common7\IDE\CommonExtensions\Microsoft\TestWindow
             $env:PATH += ";$pwd"
             cd C:\Users\circleci\project
             vstest.console.exe /Platform:x64 UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll
