 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default
    
     steps:
       - checkout #pull source code from VCS
       #- restore_cache:
       #    keys:
       #      - dotnet-packages-v1-{{ checksum "C:\Users\16479\source\repos\curly-succotash\WpfApp1"}}
       - run:
          name: "Install project dependencies"
          command: nuget restore .\WpfAppMain.sln
       #- save_cache:
       #   paths:
       #     - C:\Users\16479\source\Nuget
       #   key: dotnet-packages-v1-{{ checksum "C:\Users\16479\source\repos\curly-succotash\WpfApp1"}}
       - run:
          name: "Build using script"
          command: .\Scripts\build.ps1

       - run:
          name: "Test the app"
          command: vstest.console.exe /Platform:x64 .\UnitTestProject1\bin\Debug\netcoreapp3.1\UnitTestProject1.dll
       # TODO: sign app
